version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    validate:
      # list of validators. Specify one or more.
      - do: approvals
        min: 1
    pass:
      - do: checks
        status: 'success'
  - when: pull_request.*, pull_request_review.*
    validate:
      - do: approvals
        min: 1
      - do: label
        must_include:
          regex: 'MERGE'
    pass:
      - do: checks
        status: 'success'
  - when: pull_request.*, pull_request_review.*
    validate:
      - do: label
        must_include:
          regex: 'EMERGENCY-RELEASE'
    pass:
      - do: checks
        status: 'success'
